---
title: "3. Linear Referencing"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{linear-referencing-03}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---




```r
library(SEQKoalaDataPipeline)
library(ggplot2)
library(dplyr)
library(tidyterra)
```


## Linear referencing / dynamic segmentation

The linear referencing/ dynamic segmentation approach is used to relate
the line transects with the grid information and covariate layers. While
it can be used to derive outputs for the statistical model, the tables
generated by linear referencing itself could serve other purposes.

The toolbox for linear referencing in this package allows the user to
generate a "Route Event Layer" (also referred to as "Route Event Tables"
or "Route Table") that are the fundamental way which routes (i.e.
Transects) are represented in linear referencing.

In the linear referencing terminology, each transect is represented as a
"route". Each record in the "Route Event Layer" that stores the distance
from the start of a transect of where an "Event" occurred. An event can
be an intersection with a grid cell, or certain values within the
covariate layer. Using the `fcn_route_table` call, we can create a
"Route Event Layer" that records each "Event" and has a TransectID that
relates each event back to the transect concerned.

The function call creates a few new columns that records the attributes
of the event:

1.  FMEAS: the "From Measure", which is the distance from the start
    point of the transect where the event starts
2.  TMEAS: the "To Measure", which is the distance from the start point
    of the transect where the event ends
3.  Variable Name (e.g. GridID): the value of the event, in this case,
    the GridID of the grid cell this "Event" is describing
4.  Tlength: transect length
5.  lpercent: the percentage (proportion) of the transect that is
    covered by this event


```r
#data_dir <- "M:\\Users\\uqfcho\\Documents\\seq-koala-monitoring\\working_data"
data_dir <- "C:\\Users\\uqfcho\\Documents/seq-koala-monitoring/working_data"
fcn_set_home_dir(data_dir)
table_sf_2020 <- fcn_line_transect_sf_2020()
fcn_set_grid_size(100) # grid width/ height in meters, and generate grid in local environment
#> class       : SpatRaster 
#> dimensions  : 2467, 1759, 1  (nrow, ncol, nlyr)
#> resolution  : 100, 100  (x, y)
#> extent      : 378280, 554180, 6862464, 7109164  (xmin, xmax, ymin, ymax)
#> coord. ref. : GDA2020 / MGA zone 56 (EPSG:7856) 
#> source(s)   : memory
#> name        :  GridID 
#> min value   :       1 
#> max value   : 2311397
fishnet <- fcn_get_grid() # Retrieve grid from environment for plotting
bbox <- list(xlim = c(441430, 449400), ylim = c(6928706, 6936814), expand = F)
```


```r
route_table <- fcn_route_table_raster(fishnet, table_sf_2020)
head(route_table[route_table$lpercent < 0.5,c('TransectID', 'GridID', 'FMEAS', 'TMEAS', "Tlength", "lpercent")])
#>           TransectID  GridID     FMEAS     TMEAS  Tlength   lpercent
#> 1 1.0_0_SOL.20210810 1406599  29.63936  39.51914 484.1095 0.02040816
#> 2 1.0_0_SOL.20210810 1406600  39.51914 177.83614 484.1095 0.28571429
#> 3 1.0_0_SOL.20210810 1406601 177.83614 187.71593 484.1095 0.02040816
#> 4 1.0_0_SOL.20210810 1405037 187.71593 306.27335 484.1095 0.24489796
#> 5 1.0_0_SOL.20210810 1405038 306.27335 345.79249 484.1095 0.08163265
#> 6 1.0_0_SOL.20210810 1403475 345.79249 434.71056 484.1095 0.18367347
```

The results of the event route layer can be viewed by using
`fcn_locate_feature_from_route` which segments the line transects based
on the route event layer. This operation segments the line transects
many different small segments - it could be slow if the route event
layer is large, especially if applied to high-resolution grid cells or
route event layers of rasterized covariate layers (described below). In
many cases, the route event layer table itself is a sufficient spatial
representation of the linear referencing results, but only by doing this
step can we inspect the results visually.

Here, we see that the line transects are successfully segmented at the
border of the grid cells, as colored by different ID numbers of the Grid
where transects are colored by the last digit of the GridID:


```r
route_features <- fcn_locate_feature_from_route(route_table, table_sf_2020)
fishnet_bbox <- terra::crop(fishnet, terra::vect(bbox_sf))
fishnet_plot <- ggplot() +
  geom_spatraster(data = fishnet_bbox %>% mutate(grid_id_plot = substr(GridID, nchar(GridID), nchar(GridID))), aes(fill = grid_id_plot)) +
  do.call(coord_sf, bbox) +
  theme_bw()+
  scale_fill_brewer(palette = "Set3") +
  guides(fill = 'none')+
  theme(panel.grid = element_blank())
route_plot <- ggplot() +
  geom_sf(data = route_features, aes(color = substr(GridID, nchar(GridID), nchar(GridID)))) +
  do.call(coord_sf, bbox) +
  scale_color_brewer(palette = "Set3") +
  labs(color = "") +
  #guides(color = 'none')+
  theme_bw()+
  theme(panel.grid = element_blank())
fishnet_plot + route_plot
#> Error in `ggplot_add()`:
#> ! Can't add `route_plot` to a <ggplot> object.
```
