---
title: "5. Master data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{5. Master data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---




```r
library(SEQKoalaDataPipeline)
```

# Master data

Wrapper functions documented in the "Master data" section are designed to abstract away the details of the smaller functions, such that the most common use-cases of the package can be executed in succinct code.

We begin by extracting all tables as simple features.

```r
#data_dir <- "M:\\Users\\uqfcho\\Documents\\seq-koala-monitoring\\working_data"
data_dir <- "C:\\Users\\uqfcho\\Documents/seq-koala-monitoring/working_data"
fcn_set_home_dir(data_dir)
fcn_set_grid_size(100)
#> class       : SpatRaster 
#> dimensions  : 2467, 1759, 1  (nrow, ncol, nlyr)
#> resolution  : 100, 100  (x, y)
#> extent      : 378280, 554180, 6862464, 7109164  (xmin, xmax, ymin, ymax)
#> coord. ref. : GDA2020 / MGA zone 56 (EPSG:7856) 
#> source(s)   : memory
#> name        :  GridID 
#> min value   :       1 
#> max value   : 2311397
master <- fcn_all_tables_sf()
#> Warning in fcn_keep_distinct(transect_sf): 24 records cannot be uniquely identified with
#> SiteNumber-TransectNumber-SurveyNumber. Keeping only distinct records.
#> Warning in fcn_line_transect_sf_1996(): Line Transect: attribute join incomplete. 
#> Joined uniquely: 376. 
#> Joined at the site level: 169. 
#> Join failed: 0
#> Warning in fcn_keep_distinct(transect_sf, cols = c("SiteNumber", "TransectNumber", : 83 records cannot be
#> uniquely identified with SiteNumber-TransectNumber-SurveyNumber. Keeping only distinct records.
#> Warning in fcn_strip_transect_sf_all(): Strip Transect: attribute join incomplete. 
#> Joined uniquely: 916. 
#> Joined at the site level: 1726. 
#> Join failed: 0
```

The extracted "master" dataframe contains spatial representations of the transects in both linestring formats (single observer line transects from the newer 2020-current database) as well as other spatial representations (strip/ UAoA transects, and some line transects from 1996-2015). The `fcn_mixed_extract_raster` function handles these mixed formats simultaneously. It wraps around functions that use linear referencing approaches to extract grid information from rasters, as well as raster extraction tools, with `exactextractr` that uses C++ as a backend for quick extraction.

The function `fcn_all_transect_grid_fractions` abstracts away from that. In one function call, the algorithm executes the following:

1. Generate spatial grid

2. SQL queries to extract transect-level data

3. Joining with spatial features (if needed) or generate spatial features by coordinates

4. Buffer spatial features (if needed)

5. Calculate grid weight fractions - iterating through all buffer values by buffering each polygon and extracting its weights

6. Collating all results into a list format


```r
transect_grid <- fcn_all_transect_grid_fractions(buffer = c(0))
#> Warning in fcn_keep_distinct(transect_sf): 24 records cannot be uniquely identified with
#> SiteNumber-TransectNumber-SurveyNumber. Keeping only distinct records.
#> Warning in fcn_line_transect_sf_1996(): Line Transect: attribute join incomplete. 
#> Joined uniquely: 376. 
#> Joined at the site level: 169. 
#> Join failed: 0
#> Warning in fcn_keep_distinct(transect_sf, cols = c("SiteNumber", "TransectNumber", : 83 records cannot be
#> uniquely identified with SiteNumber-TransectNumber-SurveyNumber. Keeping only distinct records.
#> Warning in fcn_strip_transect_sf_all(): Strip Transect: attribute join incomplete. 
#> Joined uniquely: 916. 
#> Joined at the site level: 1726. 
#> Join failed: 0
```
The end result is a list containing tables of line transects, strip transect, and all of area transects. The tables are in long format, so each row corresponds to one grid cell that has an overlap with the transect. Each transect is identified uniquely by its TransectID.

Particularly the Line Transect, Strip Transect and UAoA tables contain the "GridID" and "fraction" column that contains the Grid cell that it overlaps with, and the "fraction" columns showing the fraction which the transect overlaps with. Depending on the buffer, the "fraction" is different; here we illustrate a no-buffer (0) and 2.5km (2500) buffer, in the columns 'fraction_0' and 'fraction_2500' respectively.


```r
dplyr::glimpse(transect_grid)
#> List of 4
#>  $ line_transect :'data.frame':	80679 obs. of  14 variables:
#>   ..$ db              : chr [1:80679] "1" "1" "1" "1" ...
#>   ..$ TransectID      : chr [1:80679] "109.1_1_SOL.20110901" "109.1_1_SOL.20110901" "109.1_1_SOL.20110901" "109.1_1_SOL.20110901" ...
#>   ..$ SiteID          : int [1:80679] 109 109 109 109 109 109 109 109 109 109 ...
#>   ..$ Date            : POSIXct[1:80679], format: "2011-09-01" "2011-09-01" "2011-09-01" "2011-09-01" ...
#>   ..$ TrSiteID        : num [1:80679] 1 1 1 1 1 1 1 1 1 1 ...
#>   ..$ Tlength         : num [1:80679] 278 278 278 278 278 275 275 275 275 275 ...
#>   ..$ Number_Sightings: int [1:80679] 2 2 2 2 2 0 0 0 0 0 ...
#>   ..$ Number_Observers: num [1:80679] 2 2 2 2 2 3 3 3 3 3 ...
#>   ..$ Start_Eastings  : num [1:80679] 495982 495982 495982 495982 495982 ...
#>   ..$ Start_Northings : num [1:80679] 6984954 6984954 6984954 6984954 6984954 ...
#>   ..$ End_Eastings    : num [1:80679] 495707 495707 495707 495707 495707 ...
#>   ..$ End_Northings   : num [1:80679] 6984989 6984989 6984989 6984989 6984989 ...
#>   ..$ GridID          : num [1:80679] 903602 903601 902646 902645 902644 ...
#>   ..$ fraction        : num [1:80679] 0.0204 0.2653 0.102 0.3469 0.2653 ...
#>  $ strip_transect:'data.frame':	274043 obs. of  8 variables:
#>   ..$ TransectID      : chr [1:274043] "1.1_3_ST.20101116" "1.1_3_ST.20101116" "1.1_3_ST.20101116" "1.1_3_ST.20101116" ...
#>   ..$ SiteID          : num [1:274043] 1 1 1 1 1 1 1 1 1 1 ...
#>   ..$ Date            : POSIXct[1:274043], format: "2010-11-16" "2010-11-16" "2010-11-16" "2010-11-16" ...
#>   ..$ TArea           : num [1:274043] 7.45 7.45 7.45 7.45 7.45 ...
#>   ..$ Number_Sightings: num [1:274043] 0 0 0 0 0 0 0 0 0 0 ...
#>   ..$ Number_Observers: num [1:274043] 5 5 5 5 5 5 5 5 5 5 ...
#>   ..$ GridID          : num [1:274043] 1439596 1439597 1439598 1439599 1439600 ...
#>   ..$ fraction        : num [1:274043] 0.00753 0.07986 0.06464 0.04362 0.02261 ...
#>  $ uaoa          :'data.frame':	12527 obs. of  16 variables:
#>   ..$ SiteNumber      : int [1:12527] 216 216 216 216 216 216 216 216 216 216 ...
#>   ..$ Shape_Length    : num [1:12527] 5725 5725 5725 5725 5725 ...
#>   ..$ Shape_Area      : num [1:12527] 1137144 1137144 1137144 1137144 1137144 ...
#>   ..$ db              : chr [1:12527] "1996-2015" "1996-2015" "1996-2015" "1996-2015" ...
#>   ..$ TransectID      : chr [1:12527] "216.1_99_UAoA.20110417" "216.1_99_UAoA.20110417" "216.1_99_UAoA.20110417" "216.1_99_UAoA.20110417" ...
#>   ..$ SiteID          : int [1:12527] 216 216 216 216 216 216 216 216 216 216 ...
#>   ..$ Date            : POSIXct[1:12527], format: "2011-04-17" "2011-04-17" "2011-04-17" "2011-04-17" ...
#>   ..$ TArea           : num [1:12527] 114 114 114 114 114 ...
#>   ..$ Number_Sightings: int [1:12527] 1 1 1 1 1 1 1 1 1 1 ...
#>   ..$ Number_Observers: num [1:12527] NA NA NA NA NA NA NA NA NA NA ...
#>   ..$ TransectNumber  : int [1:12527] 99 99 99 99 99 99 99 99 99 99 ...
#>   ..$ SurveyNumber    : int [1:12527] 21 21 21 21 21 21 21 21 21 21 ...
#>   ..$ SubSurveyNumber : int [1:12527] 1 1 1 1 1 1 1 1 1 1 ...
#>   ..$ TrSiteID        : num [1:12527] NA NA NA NA NA NA NA NA NA NA ...
#>   ..$ GridID          : num [1:12527] 1372965 1372966 1372967 1372968 1372969 ...
#>   ..$ fraction        : num [1:12527] 0.005845 0.005186 0.003696 0.002284 0.000751 ...
#>  $ perp_distance :'data.frame':	2642 obs. of  12 variables:
#>   ..$ db              : chr [1:2642] "1996-2015" "1996-2015" "1996-2015" "1996-2015" ...
#>   ..$ TransectID      : chr [1:2642] "1.1_1_ST.19960213" "1.1_1_ST.19960816" "1.1_1_ST.19970318" "1.1_1_ST.19970818" ...
#>   ..$ SiteID          : int [1:2642] 1 1 1 1 1 1 1 1 1 1 ...
#>   ..$ Date            : POSIXct[1:2642], format: "1996-02-13" "1996-08-16" "1997-03-18" "1997-08-18" ...
#>   ..$ TArea           : num [1:2642] 6.74 4.77 2.38 2.38 3.18 ...
#>   ..$ Number_Sightings: int [1:2642] 2 1 0 2 2 2 4 0 1 0 ...
#>   ..$ Number_Observers: num [1:2642] 6 7 4 4 5 6 4 5 5 4 ...
#>   ..$ SiteNumber      : int [1:2642] 1 1 1 1 1 1 1 1 1 1 ...
#>   ..$ TransectNumber  : int [1:2642] 1 1 1 1 1 10 10 10 10 10 ...
#>   ..$ SurveyNumber    : int [1:2642] 1 2 3 4 7 7 15 18 20 22 ...
#>   ..$ SubSurveyNumber : int [1:2642] 1 1 1 1 1 1 1 1 1 1 ...
#>   ..$ TrSiteID        : num [1:2642] NA NA NA NA NA NA NA NA NA NA ...
```

# Master extraction of covariate grid

Likewise, the covariate raster can be stored and extracted as (1) a multi-layer SpatRaster and (2) dataframe containing covariate values for each grid. The dataframe can be exported directly for use in out of sample prediction by multiplying the model coefficients with the covariate values.


```r
cov <- fcn_extract_covariate_grid()
#> [1] "Reading raster: hcapr.tif"
#> [1] "Reading raster: hcmil.tif"
#> [1] "Reading raster: hctem.tif"
#> [1] "Reading raster: hscec.tif"
#> [1] "Reading raster: hsnit.tif"
#> [1] "Reading raster: hspho.tif"
#> [1] "Reading raster: hswat.tif"
#> [1] "Reading raster: htele.tif"
#> [1] "Reading raster: htrug.tif"
#> [1] "Reading raster: htslo.tif"
#> [1] "Reading raster: hlkha_199706.tif"
#> [1] "Reading raster: hlkha_199906.tif"
#> [1] "Reading raster: hlkha_200006.tif"
#> [1] "Reading raster: hlkha_200106.tif"
#> [1] "Reading raster: hlkha_200306.tif"
#> [1] "Reading raster: hlkha_200506.tif"
#> [1] "Reading raster: hlkha_200606.tif"
#> [1] "Reading raster: hlkha_200706.tif"
#> [1] "Reading raster: hlkha_200906.tif"
#> [1] "Reading raster: hlkha_201106.tif"
#> [1] "Reading raster: hlkha_201306.tif"
#> [1] "Reading raster: hlkha_201506.tif"
#> [1] "Reading raster: hlkha_201706.tif"
#> [1] "Reading raster: hlkha_201906.tif"
#> [1] "Reading raster: hlpsz_199708.tif"
#> [1] "Reading raster: hlpsz_199803.tif"
#> [1] "Reading raster: hlpsz_199911.tif"
#> [1] "Reading raster: hlpsz_200011.tif"
#> [1] "Reading raster: hlpsz_200110.tif"
#> [1] "Reading raster: hlpsz_200210.tif"
#> [1] "Reading raster: hlpsz_200310.tif"
#> [1] "Reading raster: hlpsz_200410.tif"
#> [1] "Reading raster: hlpsz_200510.tif"
#> [1] "Reading raster: hlpsz_200610.tif"
#> [1] "Reading raster: hlpsz_200710.tif"
#> [1] "Reading raster: hlpsz_200810.tif"
#> [1] "Reading raster: hlpsz_200910.tif"
#> [1] "Reading raster: hlpsz_201010.tif"
#> [1] "Reading raster: hlpsz_201110.tif"
#> [1] "Reading raster: hlpsz_201210.tif"
#> [1] "Reading raster: hlpsz_201310.tif"
#> [1] "Reading raster: hlpsz_201410.tif"
#> [1] "Reading raster: hlpsz_201510.tif"
#> [1] "Reading raster: hlpsz_201610.tif"
#> [1] "Reading raster: hlpsz_201710.tif"
#> [1] "Reading raster: hlpsz_201810.tif"
#> [1] "Reading raster: hlpsz_201910.tif"
#> [1] "Reading raster: hlpsz_202010.tif"
#> [1] "Reading raster: hlpsz_202110.tif"
#> [1] "Reading raster: hlrem_199706.tif"
#> [1] "Reading raster: hlrem_199906.tif"
#> [1] "Reading raster: hlrem_200006.tif"
#> [1] "Reading raster: hlrem_200106.tif"
#> [1] "Reading raster: hlrem_200306.tif"
#> [1] "Reading raster: hlrem_200506.tif"
#> [1] "Reading raster: hlrem_200606.tif"
#> [1] "Reading raster: hlrem_200706.tif"
#> [1] "Reading raster: hlrem_200906.tif"
#> [1] "Reading raster: hlrem_201106.tif"
#> [1] "Reading raster: hlrem_201306.tif"
#> [1] "Reading raster: hlrem_201506.tif"
#> [1] "Reading raster: hlrem_201706.tif"
#> [1] "Reading raster: hlrem_201906.tif"
#> [1] "Reading raster: hlwdy_199607.tif"
#> [1] "Reading raster: hlwdy_199707.tif"
#> [1] "Reading raster: hlwdy_199807.tif"
#> [1] "Reading raster: hlwdy_199907.tif"
#> [1] "Reading raster: hlwdy_200007.tif"
#> [1] "Reading raster: hlwdy_200107.tif"
#> [1] "Reading raster: hlwdy_200207.tif"
#> [1] "Reading raster: hlwdy_200307.tif"
#> [1] "Reading raster: hlwdy_200407.tif"
#> [1] "Reading raster: hlwdy_200507.tif"
#> [1] "Reading raster: hlwdy_200607.tif"
#> [1] "Reading raster: hlwdy_200707.tif"
#> [1] "Reading raster: hlwdy_200807.tif"
#> [1] "Reading raster: hlwdy_200907.tif"
#> [1] "Reading raster: hlwdy_201007.tif"
#> [1] "Reading raster: hlwdy_201107.tif"
#> [1] "Reading raster: hlwdy_201207.tif"
#> [1] "Reading raster: hlwdy_201307.tif"
#> [1] "Reading raster: hlwdy_201407.tif"
#> [1] "Reading raster: hlwdy_201507.tif"
#> [1] "Reading raster: hlwdy_201607.tif"
#> [1] "Reading raster: hlwdy_201707.tif"
#> [1] "Reading raster: hlwdy_201807.tif"
#> [1] "Reading raster: hlwdy_201907.tif"
#> |---------|---------|---------|---------|=========================================                                          
cov_df <- fcn_cov_grid_df(cov, buffer = c(0))
head(cov_df)
#>   GridID    hcapr hcmil    hctem hscec hsnit hspho hswat    htele    htrug    htslo hlkha_199706 hlkha_199906
#> 1      1       NA    NA       NA    NA    NA    NA    NA       NA       NA       NA           NA           NA
#> 2      2 1546.099    63 288.9503     5  0.14 0.021 0.246 38.38303 5.397172 1.757402            6            6
#> 3      3 1547.901    63 288.0497     5  0.14 0.021 0.246 39.64868 4.874127 1.750276            6            6
#> 4      4 1545.602    63 289.0000     5  0.14 0.021 0.246 36.23794 3.985015 3.253359            6            6
#> 5      5 1538.000    63 289.0000     5  0.14 0.021 0.246 27.68007 6.137964 2.947045            6            6
#> 6      6       NA    NA       NA    NA    NA    NA    NA       NA       NA       NA           NA           NA
#>   hlkha_200006 hlkha_200106 hlkha_200306 hlkha_200506 hlkha_200606 hlkha_200706 hlkha_200906 hlkha_201106
#> 1           NA           NA           NA           NA           NA           NA           NA           NA
#> 2            6            6            6            4            4            4            4            4
#> 3            6            6            6            4            4            4            4            4
#> 4            6            6            6            4            4            4            4            4
#> 5            6            6            6            4            4            4            4            4
#> 6           NA           NA           NA           NA           NA           NA           NA           NA
#>   hlkha_201306 hlkha_201506 hlkha_201706 hlkha_201906 hlpsz_199708 hlpsz_199803 hlpsz_199911 hlpsz_200011
#> 1           NA           NA           NA           NA           NA           NA           NA           NA
#> 2            2            4            4            4      1999437      2006188           NA      1999437
#> 3            2            4            4            4           NA           NA      2019788           NA
#> 4            2            4            4            4           NA           NA      2018366           NA
#> 5            2            4            4            4           NA           NA      2017215           NA
#> 6           NA           NA           NA           NA           NA           NA      2014725           NA
#>   hlpsz_200110 hlpsz_200210 hlpsz_200310 hlpsz_200410 hlpsz_200510 hlpsz_200610 hlpsz_200710 hlpsz_200810
#> 1           NA           NA           NA           NA           NA           NA           NA           NA
#> 2     48395108           NA           NA           NA           NA           NA    129124712    129235128
#> 3           NA           NA           NA           NA           NA           NA           NA           NA
#> 4           NA           NA           NA           NA           NA           NA           NA           NA
#> 5           NA           NA           NA           NA           NA           NA           NA           NA
#> 6           NA           NA           NA           NA           NA           NA           NA           NA
#>   hlpsz_200910 hlpsz_201010 hlpsz_201110 hlpsz_201210 hlpsz_201310 hlpsz_201410 hlpsz_201510 hlpsz_201610
#> 1           NA           NA           NA           NA           NA           NA           NA           NA
#> 2    129242688    129196232    130425768    130425768    130425768    130425768    130425768    130425768
#> 3           NA           NA           NA           NA           NA           NA           NA           NA
#> 4           NA           NA           NA           NA           NA           NA           NA           NA
#> 5           NA           NA           NA           NA           NA           NA           NA           NA
#> 6           NA           NA           NA           NA           NA           NA           NA           NA
#>   hlpsz_201710 hlpsz_201810 hlpsz_201910 hlpsz_202010 hlpsz_202110 hlrem_199706 hlrem_199906 hlrem_200006
#> 1           NA           NA           NA           NA           NA           NA           NA           NA
#> 2      1932533      1932533      1932533    130417208      1932533            1            1            1
#> 3           NA           NA           NA           NA           NA            1            1            1
#> 4           NA           NA           NA           NA           NA            1            1            1
#> 5           NA           NA           NA           NA           NA            1            1            1
#> 6           NA           NA           NA           NA           NA           NA           NA           NA
#>   hlrem_200106 hlrem_200306 hlrem_200506 hlrem_200606 hlrem_200706 hlrem_200906 hlrem_201106 hlrem_201306
#> 1           NA           NA           NA           NA           NA           NA           NA           NA
#> 2            1            1            1            1            1            1            1           NA
#> 3            1            1            1            1            1            1            1           NA
#> 4            1            1            1            1            1            1            1           NA
#> 5            1            1            1            1            1            1            1           NA
#> 6           NA           NA           NA           NA           NA           NA           NA           NA
#>   hlrem_201506 hlrem_201706 hlrem_201906 hlwdy_199607 hlwdy_199707 hlwdy_199807 hlwdy_199907 hlwdy_200007
#> 1           NA           NA           NA     4.570773     4.598643     4.626514     4.626514     4.626514
#> 2            1            1            1    91.969322    92.557472    93.089882    93.089882    93.034142
#> 3            1            1            1    93.427193    94.547752    94.603493    94.603493    93.538681
#> 4            1            1            1    90.820892    91.857841    92.866920    92.866920    92.811172
#> 5            1            1            1    87.314941    86.782532    85.717712    85.717712    84.652901
#> 6           NA           NA           NA     0.000000     0.000000     0.000000     0.000000     0.000000
#>   hlwdy_200107 hlwdy_200207 hlwdy_200307 hlwdy_200407 hlwdy_200507 hlwdy_200607 hlwdy_200707 hlwdy_200807
#> 1     4.626514     4.654385     4.654385     4.682255     4.710125           NA     4.737996     4.710125
#> 2    93.006271    93.482941    93.482941    94.043213    94.603493     169.9005    95.219513    94.631363
#> 3    92.978401    91.857841    91.829971    92.362381    92.950531     167.9503    94.659233    93.566551
#> 4    92.250900    91.158211    90.597931    90.597931    91.718491     166.6518    93.959602    93.427193
#> 5    84.120491    83.588081    83.055672    83.055672    84.120491     160.0000    86.250122    86.250122
#> 6     0.000000     0.000000     0.000000     0.000000     0.000000           NA     0.000000     0.000000
#>   hlwdy_200907 hlwdy_201007 hlwdy_201107 hlwdy_201207 hlwdy_201307 hlwdy_201407 hlwdy_201507 hlwdy_201607
#> 1     4.682255     4.682255     4.682255     4.654385     4.682255     4.710125     4.765867     4.793737
#> 2    94.043213    93.987473    93.959602    93.455063    94.043213    94.659233    95.751923    96.312202
#> 3    92.418121    91.297562    90.709412    91.241821    92.334511    93.959602    94.547752    95.108032
#> 4    91.829971    90.793022    89.728210    89.728210    90.204880    90.653671    91.718491    92.223030
#> 5    86.250122    86.782532    86.782532    86.782532    85.717712    84.120491    84.120491    83.588081
#> 6     0.000000     0.000000     0.000000     0.000000     0.000000     0.000000     0.000000     0.000000
#>   hlwdy_201707 hlwdy_201807 hlwdy_201907
#> 1     4.793737     4.821608     4.821608
#> 2    96.256462    96.760994    96.733124
#> 3    94.043213    93.510811    92.950531
#> 4    92.223030    92.195152    91.607010
#> 5    83.588081    83.055672    81.990860
#> 6     0.000000     0.000000     0.000000
```

The covariate table can be joined to the transect table to produce training samples for the statistical models with covariate information.


```r
transect_grid_cov <- fcn_transect_grid_covariates(transect_grid, cov)
#> Error in FUN(X[[i]], ...): object 'state' not found
```


```r
df_datematched <- fcn_master_covariate_df_match_date(transect_grid_cov, chunk_size = 1e6)
#> Error in eval(expr, envir, enclos): object 'transect_grid_cov' not found
head(df_datematched)
#> Error in eval(expr, envir, enclos): object 'df_datematched' not found
```
