#' Linear referencing / dynamic segmentation functions
#'

#' @param feature_class SF object of the grid
#' @param line_transect SF object of the line transect
#' @export
fcn_route_table <- function(feature_class, line_transect) {
  line_transect$length = sf::st_length(line_transect$geom)
  ldnc = sf::st_intersection(line_transect, feature_class)
  ldnc$lpercent = units::drop_units((sf::st_length(ldnc)/ldnc$length))
  route_table <- sf::st_drop_geometry(ldnc)
  return(route_table)
}

#' Generate reference points and extract covariates
#' #' @param input_raster Input raster (SpatRaster)
#' @param line_transect a `sf` object with fields TransectID (unique id), Tlength (length of transect) -- generated by `fcn_line_transect_sf`
#' @param n number of sample points (including start and finish) for each transect line (precise for (100/n)% of the length -- e.g. n=50 means precise for 2% of the length)
fcn_line_sample_extract_raster <- function(input_raster, line_transect, n = 50) {
  if (length(names(input_raster)) == 1) {
    names(input_raster) <- 'value'
  }
  sample_seq <- seq(0,1,length.out=n)
  reference_points <- sf::st_line_sample(line_transect, sample = sample_seq) %>% sf::st_cast("POINT") %>% sf::st_sf()
  reference_points$TransectID <- rep(line_transect$TransectID, each = n)
  reference_points$Tlength <- rep(line_transect$Tlength, each = n)
  reference_points <- reference_points %>%
    group_by(TransectID) %>%
    mutate(distance_from_start = Tlength * sample_seq[row_number()])
  extract_table <- cbind(reference_points, terra::extract(input_raster,reference_points))
}

#' Convert covariate sample points to route layer (start and end of covariate value)
#' @param extract_table a sf feature with sampled points, i.e. output of `fcn_line_sample_extract_raster`
fcn_sample_point_to_route <- function(extract_table) {
  ## Remove points with same information as the previous column
  route_table <- extract_table %>%
    ungroup() %>%
    mutate(dup = value == dplyr::lag(value) & TransectID == dplyr::lag(TransectID)) %>%
    filter(!dup) %>%
    mutate(distance_to_end = ifelse(dplyr::lead(TransectID) == TransectID, dplyr::lead(distance_from_start), Tlength)) %>%
    mutate(segment_length = distance_to_end - distance_from_start) %>%
    dplyr::select(TransectID, Tlength, value, distance_from_start, distance_to_end, segment_length, geometry)
}

#' Get Route Table (linear referencing) for a series of linear transects
#' @param input_raster Input raster (SpatRaster)
#' @param line_transect a `sf` object with fields TransectID (unique id), Tlength (length of transect) -- generated by `fcn_line_transect_sf`
#' @param n number of sample points (including start and finish) for each transect line (precise for (100/n)% of the length -- e.g. n=50 means precise for 2% of the length)
fcn_route_table_raster <- function(input_raster, line_transect, n = 50) {
  extract_table <- fcn_line_sample_extract_raster(input_raster, line_transect, n)
  route_table <- fcn_sample_point_to_route(extract_table)
  return(route_table)
}
