# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fcnExtractElementsAtIndices <- function(row_indices, mat) {
    .Call('_SEQKoalaDataPipeline_fcnExtractElementsAtIndices', PACKAGE = 'SEQKoalaDataPipeline', row_indices, mat)
}

